// ignore_for_file: constant_identifier_names
///Generic dimens
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_1 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 18.0;

const MARGIN_MEDIUM_4 = 24.0;
const MARGIN_LARGE = 32.0;
const MARGIN_XLARGE = 48.0;
const MARGIN_XXLARGE = 94.0;
const TEXT_SMALL = 10.0;
const TEXT_SMALL_1X = 16.0;
const TEXT_REGULAR = 18.0;
const TEXT_REGULAR_1X = 24.0;
const TEXT_REGULAR_2X = 27.0;

///App Specific
const FLOATING_ACTION_BUTTON_HEIGHT = 62.0;
const MOVIE_LIST_HEIGHT = 350.0;
const MOVIE_ITEM_WIDTH = 180.0;
const MOVIE_DETAILS_SLIVER_APP_BAR_HEIGHT = 300.0;
const PLAY_BUTTON_SIZE = 60.0;
const PROFILE_IMAGE_SIZE = 60.0;
const CURVED_CONTAINER_MARGIN = 319.0;
const CURVED_CONTAINER_HEIGHT = 80.0;
const CHIP_CONTAINER_HEIGHT = 40.0;
const CAST_SECTION_HEIGHT = 100.0;
const RATING_BAR_ITEM_SIZE = 25.0;
const MOVIE_TIME_DATE_LIST_HEIGHT = 108.0;
const SNACK_ITEM_COUNT_WIDTH = 74.0;
const SNACK_ITEM_COUNT_HEIGHT = 30.0;
const PAYMENT_CARD_HEIGHT = 200.0;
const VOUCHER_LEADING_SIZE=27.0;
